# Generated by Django 5.0 on 2023-12-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalalist',
            name='title',
            field=models.CharField(default='Test title', max_length=100),
            preserve_default=False,
        ),
    ]
